name: Daily Elven News Chronicle

on:
  schedule:
    - cron: '0 5 * * *'  # 5:00 AM UTC daily
  workflow_dispatch:  # Allows manual testing

jobs:
  send-news:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install schedule requests beautifulsoup4 feedparser
    
    - name: Send daily news
      env:
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        RECIPIENT: ${{ secrets.RECIPIENT }}
      run: |
        python elven_news_bot.py
